sudo: false
language: objective-c
os: osx
osx_image: xcode10

cache:
  directories:
  - Carthage

matrix:
  include:
    - env: ACTION=test_ios12
    - env: ACTION=test_ios11
    - env: ACTION=test_tvos12
    - env: ACTION=test_tvos11
    - env: ACTION=test_ios_swift3
    - env: ACTION=test_ios_swift4
    - env: ACTION=test_tvos_swift3
    - env: ACTION=test_tvos_swift4
    - osx_image: xcode9.4
      env: ACTION=test_xcode9_ios_swift3
    - osx_image: xcode9.4
      env: ACTION=test_xcode9_ios_swift4
    - env: ACTION=pod_lint
    - env: ACTION=carthage_build

before_script:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --cache-builds --platform iOS,tvOS

script:
  - instruments -s devices # List all available simulators
  - bundle exec fastlane $ACTION

env:
  global:
    secure: k7szPQW4SmTEA29auFG3+fEeNIz6MZtYHiA+GLof5fWnTXbAEdmlxqQTgHSi+5u07cJqJPoR1k2/DN/5dMYLe5LBsMkRlx3XOUVS/Ean/bELefm270QHRXapt6mqQLHanZH9duTscUBgDgpdFxEKblc9fge24z6TyEgPHswtgT4=
