sudo: false
language: objective-c
os: osx
osx_image: xcode10.2

cache:
  directories:
  - Carthage

matrix:
  include:
    - env: ACTION=test_ios12 PLATFORM=iOS
    - env: ACTION=test_ios11 PLATFORM=iOS
    - env: ACTION=test_tvos12 PLATFORM=tvOS
    - env: ACTION=test_tvos11 PLATFORM=tvOS
    - env: ACTION=test_ios_swift4 PLATFORM=iOS
    - env: ACTION=test_ios_swift4_2 PLATFORM=iOS
    - env: ACTION=test_tvos_swift4 PLATFORM=tvOS
    - env: ACTION=test_tvos_swift4_2 PLATFORM=tvOS
    - env: ACTION=pod_lint PLATFORM="iOS,tvOS"
    - env: ACTION=carthage_build PLATFORM="iOS,tvOS"

before_script:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --cache-builds --platform iOS,tvOS

script:
  - instruments -s devices # List all available simulators
  - bundle exec fastlane $ACTION

env:
  global:
    secure: k7szPQW4SmTEA29auFG3+fEeNIz6MZtYHiA+GLof5fWnTXbAEdmlxqQTgHSi+5u07cJqJPoR1k2/DN/5dMYLe5LBsMkRlx3XOUVS/Ean/bELefm270QHRXapt6mqQLHanZH9duTscUBgDgpdFxEKblc9fge24z6TyEgPHswtgT4=
