language: objective-c
sudo: false
osx_image: xcode9

matrix:
  include:
    - os: osx
      env: ACTION=test_ios11
    - os: osx
      env: ACTION=test_ios10
    - os: osx
      env: ACTION=test_tvos11
    - os: osx
      env: ACTION=test_tvos10
    - os: osx
      osx_image: xcode8.3
      env: ACTION=test_ios10_legacy
    - os: osx
      osx_image: xcode8.3
      env: ACTION=test_tvos10_legacy
    - os: osx
      env: ACTION=pod_lint
    # - os: osx
    #   env: ACTION=carthage_build
    # - os: osx
    #   env: ACTION=spm_macos

before_script:
  - brew update
  - brew outdated carthage || brew upgrade carthage

script:
  - bundle exec fastlane $ACTION
