osx_image: xcode7.2
sudo: false
language: objective-c

env:
  global:
    - IOS_SDK=iphonesimulator9.2
    - IOS_SCHEME="DTTableViewManager-iOS"
    - TVOS_SDK=appletvsimulator9.1
    - TVOS_SCHEME="DTTableViewManager-tvOS"
  matrix:
      - DESTINATION="OS=9.2,name=iPad 2"         SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"
      - DESTINATION="OS=9.2,name=iPad Air"       SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"
      - DESTINATION="OS=9.2,name=iPhone 5"       SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"
      - DESTINATION="OS=9.2,name=iPhone 6s"      SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"
      - DESTINATION="OS=8.4,name=iPhone 6"       SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"
      - DESTINATION="OS=8.4,name=iPad Air"       SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"
      - DESTINATION="OS=9.1,name=Apple TV 1080p" SDK="$TVOS_SDK" SCHEME="$TVOS_SCHEME"

before_install:
    - cd Example

script:
    - set -o pipefail
    - git submodule update --init --recursive
    - xcodebuild -version
    - xcodebuild -workspace DTTableViewManager.xcworkspace -scheme "$SCHEME" -configuration Debug -sdk "$SDK" -destination "$DESTINATION" clean build test -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO "IDEBuildOperationMaxNumberOfConcurrentCompileTasks=`sysctl -n hw.ncpu`" | xcpretty
    - xcodebuild -workspace DTTableViewManager.xcworkspace -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" test -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO "IDEBuildOperationMaxNumberOfConcurrentCompileTasks=`sysctl -n hw.ncpu`"
after_success:
    - bash <(curl -s https://codecov.io/bash)
