name: "CI"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  iOS-Xcode-12:
    name: Test iOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer
    strategy:
      matrix:
        destination: ["test_ios14"] #,"test_ios12"]
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: bundle install
      - name: List simulators
        run: instruments -s devices
      - name: iOS - ${{ matrix.destination }}
        run: bundle exec fastlane ${{ matrix.destination }}
  tvOS-Xcode-12:
    name: Test tvOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer
    strategy:
      matrix:
        destination: ["test_tvos14"] #,"test_tvos12"]
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: bundle install
      - name: tvOS - ${{ matrix.destination }}
        run: bundle exec fastlane ${{ matrix.destination }}
  cocoapods:
    name: Lint podspec
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: bundle install
      - name: CocoaPods spec lint
        run: bundle exec fastlane pod_lint
